### PR TITLE
Fix outdated people docs

### LINKED ISSUE #1893: Docs about /people/search old
We now only expose staff information not students, making the documentation wrong.

### PR DESCRIPTION
**Pull request by hueyy**
Resolves #1893

### CODE REVIEW

File: frontend/src/components/documentation/Routes/Search/GetPeople.jsx [hunk 1]
```diff
@@ -44,95 +47,124 @@ let response = `{
...
+              description={`
+                Since only staff are returned through this API,
+                this should always be Staff.`
+              }
+            />
+            <Cell
+              name="department"
+              extra="string"
+              example="UCL Medical School"
+              description="The department the student studies or works under."
```
Comment (zipy124) [inline frontend/src/components/documentation/Routes/Search/GetPeople.jsx]: @hueyy This should also remove the reference to students.

Comment (hueyy) [reply frontend/src/components/documentation/Routes/Search/GetPeople.jsx]: good point
